### ISSUE TITLE
httpError 403 Forbidden when using iphone's wkwebkit

### ISSUE THREAD

**Issue by NiyazKhasanov1994** [k3rn31p4nic/google-translate-api#1]
I got no error when using in Chrome on mac but it throws sad error when using this package from iphone(

**Comment by k3rn31p4nic** [comment]
@NiyazKhasanov1994 Sorry for my late response, somehow I didn't received any notification for this.

If you're still having the issue, can you give more details on how you're implementing it & using it? That'll help me find your issue.

**Comment by k3rn31p4nic** [comment]
Actually this error is now happening in every device/environment.
