### ISSUE TITLE
HTTPError 302  after regular translation

### ISSUE THREAD

**Issue by kalpak44** [k3rn31p4nic/google-translate-api#12]
After a few successful translates start to fail with warnings:
`
 node index.js
{ HTTPError
    at translate (C:\Users\User\Desktop\node_test\node_modules\@k3rn31p4nic\google-translate-api\src\index.js:143:19)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError', statusCode: 302, statusMessage: 'Found' }
`

index.js:

`
translate(articleRU, { from: 'ru', to: 'bg' }).then(res => { 
    console.log(res.text);
}).catch(err => {
  console.error(err);
});
`

**Comment by k3rn31p4nic** [comment]
Are you still getting the error?

**Comment by cheesits456** [comment]
I ran into the same issue while using this for a live translator that I implemented into my Discord bot
![image](https://user-images.githubusercontent.com/35486894/75486610-af8a5600-5961-11ea-9996-9627f7183afd.png)

**Comment by k3rn31p4nic** [comment]
Can you give a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by kalpak44** [comment]
I did not watch the implementation, but the requests themselves towards Google translator are banned with frequent use. The first several times is ok, after several times start to throw different errors

In case like this
```
function index(){
	var things = ['Rock', 'Paper', 'Scissor', 'Apple', 'Appearance', 'Announce'];
	var thing = things[Math.floor(Math.random()*things.length)];
	console.log("original: " + thing)
	translate(thing, { from: 'en', to: 'bg' }).then(res => {
		  console.log("translated: " + res.text)
		}).catch(err => {
		  console.error(err);
	});
	setTimeout(index, 5000);
}

index()
```
there throws something like:
```
{ HTTPError
    at translate (C:\Users\User\Desktop\node_test\node_modules\@k3rn31p4nic\google-translate-api\src\index.js:143:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  statusCode: 429,
  statusMessage: 'Too Many Requests' }

```
If text is longer then error is another:

```
{ HTTPError
    at translate (C:\Users\User\Desktop\node_test\node_modules\@k3rn31p4nic\google-translate-api\src\index.js:143:8)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError', statusCode: 302, statusMessage: 'Found' }
```
Do you know how often you can make requests without errors?

**Comment by cheesits456** [comment]
Hmm I've been looking into this problem and it seems to be pretty common - from what I've gathered so far, it seems the only way to get around the errors is either to slow down your requests, or use proxies so you don't get ratelimmited by Google

**Comment by k3rn31p4nic** [comment]
> Do you know how often you can make requests without errors?

Nope. As this isn't an official API, we don't know about their rate limits.

**Comment by k3rn31p4nic** [comment]
> If text is longer then error is another

How long of a text are you trying to send?

**Comment by k3rn31p4nic** [comment]
Closing it as it has become stale. Feel free to reopen if you're still facing the issue and have reproduction steps.
