### ISSUE TITLE
error 429 after few testing

### ISSUE THREAD

**Issue by LynxKik** [k3rn31p4nic/google-translate-api#13]
I am getting this error after doing a few tests

{ name : HTTPError , statusCode :429, statusMessage : Too Many Requests }

**Comment by cheesits456** [comment]
429 is for ratelimits, so I'd assume that whatever you're doing, you're doing it too fast, and google is telling you to slow down

**Comment by k3rn31p4nic** [comment]
This is to prevent abuse of free services. The only thing you can do here is make requests using proxies, and change to a different proxy if you get 429 or wait a few seconds. But if this solution is worth the effort depends on the application.
