### ISSUE TITLE
BAD_REQUEST

### ISSUE THREAD

**Issue by cristea2017** [k3rn31p4nic/google-translate-api#17]
Error
    at /Users/asd/node_modules/google-translate-api/index.js:105:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'BAD_REQUEST'
}

**Comment by k3rn31p4nic** [comment]
Can you give a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by cristea2017** [comment]
> Can you give a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

const translate = require("google-translate-api");

translate("Thank you", { from: "en", to: "fr" })
  .then((res) => {
    console.log(res.text); // OUTPUT: Je vous remercie
    console.log(res.from.autoCorrected); // OUTPUT: true
    console.log(res.from.text.value); // OUTPUT: [Thank] you
    console.log(res.from.text.didYouMean); // OUTPUT: false
  })
  .catch((err) => {
    console.error(err);
  });

**Comment by k3rn31p4nic** [comment]
You need to use `@k3rn31p4nic/google-translate-api`. If you mean to use `google-translate-api` instead, you're in the wrong repo.
