### ISSUE TITLE
statusCode: 429 statusMessage: 'Too Many Requests'

### ISSUE THREAD

**Issue by thawon** [k3rn31p4nic/google-translate-api#18]
Hi, when I make a request, I get the status code 429 with too many request. 
Is there a limitation on the API call? if yes, would you tell me what they are? so I will be aware of them. thanks a lot.

**Comment by k3rn31p4nic** [comment]
Yeah, google definitely has some rate limits in place to prevent abuse. Since this isn't official, I can't exactly say what the rate limits for this exactly are.

**Comment by AidanWelch** [comment]
The `single` translate endpoint has a much stricter limit than the limit that may not even exist on the `batch` endpoint.  This packager only implements `single`
